"use client";

import { useState, useEffect } from "react";
import {
  ArrowLeft,
  Cpu,
  Download,
  Edit3,
  ExternalLink,
  FileCode,
  FileText,
  ShieldAlert,
} from "lucide-react";
import { Button } from "@acme/ui/button";
import { Card } from "@acme/ui/card";
import { calculateFit, type Job } from "../_lib/mock-data";

interface GeneratorViewProps {
  job: Job;
  userDump: string;
  onBack: () => void;
}

export function GeneratorView({ job, userDump, onBack }: GeneratorViewProps) {
  const [activeTab, setActiveTab] = useState<"preview" | "latex" | "cover">(
    "preview",
  );
  const [isGenerating, setIsGenerating] = useState(true);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    // Simulate generation steps for "Tech Demo" feel
    const intervals = [
      { t: 500, p: 20 },
      { t: 1000, p: 40 },
      { t: 1500, p: 60 },
      { t: 2000, p: 80 },
      { t: 2500, p: 100 },
    ];

    intervals.forEach(({ t, p }) => {
      setTimeout(() => {
        setProgress(p);
        if (p === 100) setIsGenerating(false);
      }, t);
    });
  }, []);

  const latexCode = `
% Auto-generated by KerjaFlow via Claude Sonnet
\\documentclass[a4paper,10pt]{article}
\\usepackage{titlesec}
\\usepackage{geometry}
\\usepackage{enumitem}
\\geometry{left=1in, right=1in, top=1in, bottom=1in}

\\begin{document}

\\section*{Candidate Name}
\\textbf{Role Applied:} ${job.title} at ${job.company}

\\section*{Professional Summary}
Results-oriented professional with ${userDump.includes("4 years") ? "4 years" : "proven"} experience.
Specific expertise in ${job.keywords.slice(0, 2).join(" and ")}, directly matching the requirements for the ${job.title} role.

\\section*{Relevant Experience}
\\textbf{TechMy Sdn Bhd} \\hfill 2020--2022 \\\\
\\textit{Frontend Developer}
\\begin{itemize}[noitemsep]
    \\item Leveraged ${job.tags[0] || "React"} to build scalable systems.
    \\item (AI Tailored): Optimized performance, aligning with ${job.company}'s focus on quality.
\\end{itemize}

\\end{document}
  `;

  const coverLetter = `
Dear Hiring Manager at ${job.company},

I am writing to express my strong interest in the ${job.title} position based in ${job.location}.

I noticed in the job description that ${job.company} values "${job.culture_raw || "innovation"}". This resonates with me because in my previous role, I always prioritized transparent communication and high-quality code delivery.

With my background in ${job.keywords[0]} and ${job.keywords[1]}, I am confident I can hit the ground running.

Thank you for your time and consideration.

Sincerely,
[Candidate Name]
  `;

  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh]">
        <div className="w-64 bg-slate-200 rounded-full h-2 mb-8 overflow-hidden">
          <div
            className="bg-indigo-600 h-full transition-all duration-300 ease-out"
            style={{ width: `${progress}%` }}
          ></div>
        </div>
        <div className="flex flex-col items-center space-y-4 animate-in fade-in slide-in-from-bottom-4">
          <Cpu size={48} className="text-indigo-600 animate-pulse" />
          <h2 className="text-2xl font-bold text-slate-800">
            Claude Sonnet is Thinking...
          </h2>
          <div className="text-sm text-slate-500 font-mono flex flex-col items-center space-y-1">
            <p className={progress > 20 ? "text-green-600" : "text-slate-400"}>
              ✓ Analyzing &quot;Master Dump&quot; vs Job Spec
            </p>
            <p className={progress > 40 ? "text-green-600" : "text-slate-400"}>
              ✓ Identifying keywords: {job.keywords.slice(0, 3).join(", ")}
            </p>
            <p className={progress > 60 ? "text-green-600" : "text-slate-400"}>
              ✓ Drafting Cover Letter
            </p>
            <p className={progress > 80 ? "text-green-600" : "text-slate-400"}>
              ✓ Compiling LaTeX to PDF...
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto h-[85vh] flex flex-col animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <button
          onClick={onBack}
          className="flex items-center text-slate-500 hover:text-slate-800 transition-colors"
        >
          <ArrowLeft size={16} className="mr-1" /> Back to Dashboard
        </button>
        <div className="flex items-center gap-3">
          <a
            href={job.link}
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-2 bg-slate-900 hover:bg-slate-700 text-white px-5 py-2.5 rounded-lg shadow-sm font-bold transition-all"
          >
            Apply on Hiredly <ExternalLink size={16} />
          </a>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-6 h-full pb-8">
        {/* Left: Job Context */}
        <div className="col-span-12 md:col-span-4 flex flex-col gap-4 h-full overflow-hidden">
          {/* Job Details Card */}
          <Card className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm">
            <div className="mb-4">
              <h1 className="text-xl font-bold text-slate-900 leading-tight mb-1">
                {job.title}
              </h1>
              <p className="text-slate-500 font-medium">{job.company}</p>
            </div>

            <div className="bg-green-50 p-3 rounded-lg border border-green-100 flex items-center justify-between mb-4">
              <span className="text-xs font-bold text-green-700 uppercase">
                Fit Score
              </span>
              <span className="text-2xl font-black text-green-600">
                {calculateFit(job.keywords, userDump)}%
              </span>
            </div>

            {job.risk_level === "High Risk" && (
              <div className="bg-red-50 p-3 rounded-lg border border-red-100 mb-4">
                <h4 className="flex items-center text-red-800 font-bold text-xs mb-1">
                  <ShieldAlert size={12} className="mr-1" /> Caution: Red Flags
                </h4>
                <ul className="pl-4 list-disc space-y-0.5">
                  {job.red_flags.map((flag, idx) => (
                    <li key={idx} className="text-[10px] text-red-700">
                      {flag}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="text-xs text-slate-500 leading-relaxed border-t border-slate-100 pt-3 max-h-32 overflow-y-auto">
              {job.description}
            </div>
          </Card>

          {/* AI Insight Card */}
          <Card className="bg-indigo-50 p-5 rounded-xl border border-indigo-100 flex-1 overflow-auto">
            <div className="flex items-center gap-2 mb-3">
              <Cpu size={18} className="text-indigo-600" />
              <h3 className="font-bold text-indigo-900 text-sm">
                Tailoring Strategy
              </h3>
            </div>
            <p className="text-sm text-indigo-800 mb-2 leading-relaxed">
              I&apos;ve rephrased your experience at <strong>TechMy</strong> to
              highlight <strong>{job.tags[0]}</strong>, which is listed as a
              critical requirement.
            </p>
            <p className="text-sm text-indigo-800 leading-relaxed">
              Since this is a senior role, I emphasized &quot;team
              leadership&quot; over your &quot;freelance&quot; work in the
              summary section.
            </p>
          </Card>
        </div>

        {/* Right: Generator Output */}
        <div className="col-span-12 md:col-span-8 flex flex-col bg-slate-800 rounded-xl overflow-hidden shadow-2xl border border-slate-700">
          {/* Toolbar */}
          <div className="bg-slate-900 p-3 flex justify-between items-center border-b border-slate-700">
            <div className="flex gap-1">
              <button
                onClick={() => setActiveTab("preview")}
                className={`px-3 py-1.5 rounded-md text-xs font-bold flex items-center gap-2 transition-all ${
                  activeTab === "preview"
                    ? "bg-slate-700 text-white shadow-inner"
                    : "text-slate-400 hover:text-white hover:bg-slate-800"
                }`}
              >
                <FileText size={14} /> PDF Preview
              </button>
              <button
                onClick={() => setActiveTab("cover")}
                className={`px-3 py-1.5 rounded-md text-xs font-bold flex items-center gap-2 transition-all ${
                  activeTab === "cover"
                    ? "bg-slate-700 text-white shadow-inner"
                    : "text-slate-400 hover:text-white hover:bg-slate-800"
                }`}
              >
                <Edit3 size={14} /> Cover Letter
              </button>
              <button
                onClick={() => setActiveTab("latex")}
                className={`px-3 py-1.5 rounded-md text-xs font-bold flex items-center gap-2 transition-all ${
                  activeTab === "latex"
                    ? "bg-slate-700 text-white shadow-inner"
                    : "text-slate-400 hover:text-white hover:bg-slate-800"
                }`}
              >
                <FileCode size={14} /> LaTeX Source
              </button>
            </div>
            <button className="text-emerald-400 text-xs font-bold flex items-center gap-2 hover:text-emerald-300">
              <Download size={14} /> Download PDF
            </button>
          </div>

          {/* Content Area */}
          <div className="flex-1 bg-white overflow-y-auto font-serif relative">
            {activeTab === "preview" && (
              <div className="max-w-[210mm] mx-auto p-12 bg-white min-h-full shadow-lg">
                <div className="text-center border-b-2 border-gray-800 pb-6 mb-6">
                  <h2 className="text-3xl font-bold uppercase tracking-widest text-gray-900">
                    Demo User
                  </h2>
                  <div className="text-sm text-gray-600 mt-2 flex justify-center gap-4">
                    <span>Subang Jaya, Malaysia</span>
                    <span>•</span>
                    <span>candidate@email.com</span>
                    <span>•</span>
                    <span>linkedin.com/in/demouser</span>
                  </div>
                </div>

                <div className="mb-6">
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-2">
                    Professional Summary
                  </h3>
                  <p className="text-sm leading-relaxed text-gray-800">
                    Results-oriented Software Engineer with a proven track
                    record of delivering robust web solutions. Possesses strong
                    expertise in{" "}
                    <strong>{job.keywords.slice(0, 3).join(", ")}</strong>,
                    directly aligning with the technical requirements for the{" "}
                    <strong>{job.title}</strong> role at{" "}
                    <strong>{job.company}</strong>. Committed to writing clean,
                    maintainable code and fostering collaborative team
                    environments.
                  </p>
                </div>

                <div className="mb-6">
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-3">
                    Relevant Experience
                  </h3>

                  <div className="mb-4">
                    <div className="flex justify-between items-baseline mb-1">
                      <h4 className="font-bold text-gray-900 text-base">
                        Frontend Developer
                      </h4>
                      <span className="text-sm text-gray-600 font-medium">
                        2020 - 2022
                      </span>
                    </div>
                    <p className="text-sm text-gray-700 italic mb-2">
                      TechMy Sdn Bhd
                    </p>
                    <ul className="list-disc list-outside ml-4 text-sm space-y-1.5 text-gray-700">
                      <li>
                        Spearheaded the development of a client-facing dashboard
                        using <strong>{job.tags[0] || "React"}</strong>,
                        reducing page load times by 40%.
                      </li>
                      <li>
                        Collaborated with cross-functional teams to implement{" "}
                        <strong>{job.tags[1] || "RESTful APIs"}</strong>,
                        ensuring seamless data integration.
                      </li>
                      <li>
                        Mentored junior developers on best practices in{" "}
                        {job.keywords[1] || "modern web development"}.
                      </li>
                    </ul>
                  </div>

                  <div className="mb-4">
                    <div className="flex justify-between items-baseline mb-1">
                      <h4 className="font-bold text-gray-900 text-base">
                        Freelance Web Developer
                      </h4>
                      <span className="text-sm text-gray-600 font-medium">
                        2018 - 2020
                      </span>
                    </div>
                    <p className="text-sm text-gray-700 italic mb-2">
                      Self-Employed
                    </p>
                    <ul className="list-disc list-outside ml-4 text-sm space-y-1.5 text-gray-700">
                      <li>
                        Delivered 15+ custom WordPress and HTML websites for
                        local SMEs, ensuring mobile responsiveness and SEO
                        optimization.
                      </li>
                      <li>
                        Managed client requirements and project timelines
                        effectively.
                      </li>
                    </ul>
                  </div>
                </div>

                <div>
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-2">
                    Skills
                  </h3>
                  <p className="text-sm text-gray-700">
                    <strong>Technical:</strong> {job.keywords.join(", ")}, SQL,
                    Git, Tailwind CSS.
                    <br />
                    <strong>Languages:</strong> English (Native), Malay
                    (Fluent).
                  </p>
                </div>
              </div>
            )}

            {activeTab === "cover" && (
              <div className="max-w-[210mm] mx-auto p-12 bg-white min-h-full font-sans text-slate-800 leading-relaxed whitespace-pre-wrap">
                {coverLetter}
              </div>
            )}

            {activeTab === "latex" && (
              <div className="bg-[#1e1e1e] text-[#d4d4d4] p-6 min-h-full font-mono text-xs overflow-auto">
                <pre>{latexCode}</pre>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
