"use client";

import { useState, useEffect } from "react";
import {
  ArrowLeft,
  Cpu,
  Download,
  Edit3,
  ExternalLink,
  FileCode,
  FileText,
  ShieldAlert,
  Sparkles,
} from "lucide-react";
import { Button } from "@acme/ui/button";
import { calculateFit, type Job } from "../_lib/mock-data";

interface GeneratorViewProps {
  job: Job;
  userDump: string;
  onBack: () => void;
  userId?: any;
  userName?: string;
  userEmail?: string;
}

export function GeneratorView({ job, userDump, onBack, userId, userName, userEmail }: GeneratorViewProps) {
  const [activeTab, setActiveTab] = useState<"preview" | "latex" | "cover">(
    "preview",
  );
  const [isGenerating, setIsGenerating] = useState(true);
  const [progress, setProgress] = useState(0);
  const [generatedResume, setGeneratedResume] = useState<any>(null);
  const [generatedCoverLetter, setGeneratedCoverLetter] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    generateDocuments();
  }, []);

  const generateDocuments = async () => {
    try {
      setIsGenerating(true);
      setProgress(10);

      // Generate tailored resume
      const resumeResponse = await fetch("/api/generate-resume", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          resumeContent: userDump,
          jobDescription: job.description || "",
          jobPosition: job.position || job.title || "",
          jobCompany: job.company || "",
        }),
      });

      setProgress(50);

      if (!resumeResponse.ok) {
        throw new Error("Failed to generate resume");
      }

      const resumeData = await resumeResponse.json();
      setGeneratedResume(resumeData);

      setProgress(70);

      // Generate cover letter
      const coverLetterResponse = await fetch("/api/generate-cover-letter", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          resumeContent: userDump,
          jobDescription: job.description || "",
          jobPosition: job.position || job.title || "",
          jobCompany: job.company || "",
        }),
      });

      setProgress(90);

      if (!coverLetterResponse.ok) {
        throw new Error("Failed to generate cover letter");
      }

      const coverLetterData = await coverLetterResponse.json();
      setGeneratedCoverLetter(coverLetterData);

      setProgress(100);
      setIsGenerating(false);
    } catch (err) {
      console.error("Error generating documents:", err);
      setError(err instanceof Error ? err.message : "Failed to generate documents");
      setIsGenerating(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!generatedResume || !userName || !userEmail) {
      alert("Resume data not ready. Please wait for generation to complete.");
      return;
    }

    try {
      setIsDownloading(true);

      const response = await fetch("/api/generate-pdf", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          userName,
          userEmail,
          summary: generatedResume.summary,
          experience: generatedResume.experience,
          skills: generatedResume.skills,
          education: generatedResume.education,
          additionalSections: generatedResume.additionalSections,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate PDF");
      }

      // Convert response to blob
      const blob = await response.blob();

      // Create download link
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `resume-${userName.replace(/\s+/g, "-")}-${job.company}.pdf`;
      document.body.appendChild(a);
      a.click();

      // Cleanup
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error("Error downloading PDF:", err);
      alert("Failed to download PDF. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  };

  const latexCode = `
% Auto-generated by KerjaFlow via Claude Sonnet
\\documentclass[a4paper,10pt]{article}
\\usepackage{titlesec}
\\usepackage{geometry}
\\usepackage{enumitem}
\\geometry{left=1in, right=1in, top=1in, bottom=1in}

\\begin{document}

\\section*{Candidate Name}
\\textbf{Role Applied:} ${job.title || job.position} at ${job.company}

\\section*{Professional Summary}
Results-oriented professional with ${userDump.includes("4 years") ? "4 years" : "proven"} experience.
Specific expertise in ${job.keywords?.slice(0, 2).join(" and ") || "relevant technologies"}, directly matching the requirements for the ${job.title || job.position} role.

\\section*{Relevant Experience}
\\textbf{TechMy Sdn Bhd} \\hfill 2020--2022 \\\\
\\textit{Frontend Developer}
\\begin{itemize}[noitemsep]
    \\item Leveraged ${job.tags?.[0] || "React"} to build scalable systems.
    \\item (AI Tailored): Optimized performance, aligning with ${job.company}'s focus on quality.
\\end{itemize}

\\end{document}
  `;

  const coverLetter = `
Dear Hiring Manager at ${job.company},

I am writing to express my strong interest in the ${job.title || job.position} position based in ${job.location}.

I noticed in the job description that ${job.company} values "${job.culture_raw || "innovation"}". This resonates with me because in my previous role, I always prioritized transparent communication and high-quality code delivery.

With my background in ${job.keywords?.[0] || "software development"} and ${job.keywords?.[1] || "problem solving"}, I am confident I can hit the ground running.

Thank you for your time and consideration.

Sincerely,
[Candidate Name]
  `;

  /* #region LOADING STATE */
  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh] relative">
        <div className="absolute top-[10%] left-[30%] w-[400px] h-[400px] bg-brand-600/10 blur-[100px] rounded-full pointer-events-none" />

        <div className="w-64 bg-slate-800 rounded-full h-2 mb-8 overflow-hidden relative z-10">
          <div
            className="bg-gradient-to-r from-brand-500 to-accent-500 h-full transition-all duration-300 ease-out"
            style={{ width: `${progress}%` }}
          />
        </div>
        <div className="flex flex-col items-center space-y-4 animate-in fade-in slide-in-from-bottom-4 relative z-10">
          <div className="relative">
            <Cpu size={48} className="text-brand-400 animate-pulse" />
            <div className="absolute inset-0 bg-brand-500 blur-xl opacity-30 animate-pulse" />
          </div>
          <h2 className="text-2xl font-bold text-white">
            Claude Sonnet is Thinking...
          </h2>
          <div className="text-sm text-slate-400 font-mono flex flex-col items-center space-y-1">
            <p className={progress > 20 ? "text-green-400" : "text-slate-500"}>
              ✓ Analyzing &quot;Master Dump&quot; vs Job Spec
            </p>
            <p className={progress > 50 ? "text-green-400" : "text-slate-500"}>
              ✓ Generating tailored resume...
            </p>
            <p className={progress > 70 ? "text-green-400" : "text-slate-500"}>
              ✓ Drafting Cover Letter
            </p>
            <p className={progress > 90 ? "text-green-400" : "text-slate-500"}>
              ✓ Finalizing documents...
            </p>
          </div>
        </div>
      </div>
    );
  }
  /* #endregion */

  /* #region ERROR STATE */
  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh]">
        <div className="text-center">
          <ShieldAlert size={48} className="text-red-400 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-white mb-2">Generation Failed</h2>
          <p className="text-slate-400 mb-4">{error}</p>
          <Button onClick={generateDocuments} className="bg-brand-600 hover:bg-brand-500">Try Again</Button>
        </div>
      </div>
    );
  }
  /* #endregion */

  /* #region MAIN VIEW */
  return (
    <div className="max-w-6xl mx-auto h-[85vh] flex flex-col animate-in fade-in duration-500 relative">
      {/* Ambient Effects */}
      <div className="absolute top-[-10%] right-[20%] w-[400px] h-[400px] bg-brand-600/5 blur-[100px] rounded-full pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between mb-4 relative z-10">
        <button
          onClick={onBack}
          className="flex items-center text-slate-400 hover:text-white transition-colors"
        >
          <ArrowLeft size={16} className="mr-1" /> Back to Dashboard
        </button>
        <div className="flex items-center gap-3">
          <a
            href={job.link || job.url}
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-2 bg-white hover:bg-slate-100 text-slate-900 px-5 py-2.5 rounded-xl shadow-lg font-bold transition-all"
          >
            Apply on Hiredly <ExternalLink size={16} />
          </a>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-6 h-full pb-8 relative z-10">
        {/* Left: Job Context */}
        <div className="col-span-12 md:col-span-4 flex flex-col gap-4 h-full overflow-hidden">
          {/* Job Details Card */}
          <div className="glass-card p-5 rounded-2xl">
            <div className="mb-4">
              <h1 className="text-xl font-bold text-white leading-tight mb-1">
                {job.title || job.position}
              </h1>
              <p className="text-slate-400 font-medium">{job.company}</p>
            </div>

            <div className="bg-green-500/10 p-3 rounded-xl border border-green-500/20 flex items-center justify-between mb-4">
              <span className="text-xs font-bold text-green-400 uppercase flex items-center gap-1">
                <Sparkles className="w-3 h-3" /> Fit Score
              </span>
              <span className="text-2xl font-black text-green-400">
                {calculateFit(job.keywords || [], userDump)}%
              </span>
            </div>

            {job.risk_level === "High Risk" && job.red_flags && (
              <div className="bg-red-500/10 p-3 rounded-xl border border-red-500/20 mb-4">
                <h4 className="flex items-center text-red-400 font-bold text-xs mb-1">
                  <ShieldAlert size={12} className="mr-1" /> Caution: Red Flags
                </h4>
                <ul className="pl-4 list-disc space-y-0.5">
                  {job.red_flags.map((flag, idx) => (
                    <li key={idx} className="text-[10px] text-red-300">
                      {flag}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="text-xs text-slate-400 leading-relaxed border-t border-slate-700/50 pt-3 max-h-32 overflow-y-auto">
              {job.description}
            </div>
          </div>

          {/* AI Insight Card */}
          <div className="glass-panel p-5 rounded-2xl flex-1 overflow-auto border border-brand-500/20">
            <div className="flex items-center gap-2 mb-3">
              <Cpu size={18} className="text-brand-400" />
              <h3 className="font-bold text-white text-sm">
                Tailoring Strategy
              </h3>
            </div>
            <p className="text-sm text-slate-300 mb-2 leading-relaxed">
              I&apos;ve rephrased your experience at <strong className="text-brand-300">TechMy</strong> to
              highlight <strong className="text-brand-300">{job.tags?.[0] || "relevant skills"}</strong>, which is listed as a
              critical requirement.
            </p>
            <p className="text-sm text-slate-300 leading-relaxed">
              Since this is a senior role, I emphasized &quot;team
              leadership&quot; over your &quot;freelance&quot; work in the
              summary section.
            </p>
          </div>
        </div>

        {/* Right: Generator Output */}
        <div className="col-span-12 md:col-span-8 flex flex-col bg-slate-900 rounded-2xl overflow-hidden shadow-2xl border border-slate-800">
          {/* Toolbar */}
          <div className="bg-slate-950 p-3 flex justify-between items-center border-b border-slate-800">
            <div className="flex gap-1">
              <button
                onClick={() => setActiveTab("preview")}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${
                  activeTab === "preview"
                    ? "bg-slate-800 text-white"
                    : "text-slate-400 hover:text-white hover:bg-slate-800/50"
                }`}
              >
                <FileText size={14} /> PDF Preview
              </button>
              <button
                onClick={() => setActiveTab("cover")}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${
                  activeTab === "cover"
                    ? "bg-slate-800 text-white"
                    : "text-slate-400 hover:text-white hover:bg-slate-800/50"
                }`}
              >
                <Edit3 size={14} /> Cover Letter
              </button>
              <button
                onClick={() => setActiveTab("latex")}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${
                  activeTab === "latex"
                    ? "bg-slate-800 text-white"
                    : "text-slate-400 hover:text-white hover:bg-slate-800/50"
                }`}
              >
                <FileCode size={14} /> LaTeX Source
              </button>
            </div>
            <button
              onClick={handleDownloadPDF}
              disabled={isDownloading || isGenerating}
              className="text-accent-400 text-xs font-bold flex items-center gap-2 hover:text-accent-300 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Download size={14} className={isDownloading ? "animate-bounce" : ""} />
              {isDownloading ? "Generating PDF..." : "Download PDF"}
            </button>
          </div>

          {/* Content Area - PDF Preview stays white for realistic appearance */}
          <div className="flex-1 bg-slate-800 overflow-y-auto font-serif relative">
            {activeTab === "preview" && (
              <div className="max-w-[210mm] mx-auto my-6 p-12 bg-white min-h-full shadow-2xl rounded-lg">
                <div className="text-center border-b-2 border-gray-800 pb-6 mb-6">
                  <h2 className="text-3xl font-bold uppercase tracking-widest text-gray-900">
                    {userName || "Your Name"}
                  </h2>
                  <div className="text-sm text-gray-600 mt-2 flex justify-center gap-4">
                    <span>Malaysia</span>
                    {userEmail && (
                      <>
                        <span>•</span>
                        <span>{userEmail}</span>
                      </>
                    )}
                  </div>
                </div>

                <div className="mb-6">
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-2">
                    Professional Summary
                  </h3>
                  <p className="text-sm leading-relaxed text-gray-800">
                    {generatedResume?.summary || "Generating professional summary..."}
                  </p>
                </div>

                <div className="mb-6">
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-3">
                    Relevant Experience
                  </h3>

                  {generatedResume?.experience?.map((exp: any, idx: number) => (
                    <div key={idx} className="mb-4">
                      <div className="flex justify-between items-baseline mb-1">
                        <h4 className="font-bold text-gray-900 text-base">
                          {exp.position}
                        </h4>
                        <span className="text-sm text-gray-600 font-medium">
                          {exp.duration}
                        </span>
                      </div>
                      <p className="text-sm text-gray-700 italic mb-2">
                        {exp.company}
                      </p>
                      <ul className="list-disc list-outside ml-4 text-sm space-y-1.5 text-gray-700">
                        {exp.achievements?.map((achievement: string, aidx: number) => (
                          <li key={aidx}>{achievement}</li>
                        ))}
                      </ul>
                    </div>
                  )) || <p className="text-sm text-gray-500">Generating experience section...</p>}
                </div>

                <div className="mb-6">
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-2">
                    Skills
                  </h3>
                  <p className="text-sm text-gray-700">
                    {generatedResume?.skills?.join(", ") || "Generating skills..."}
                  </p>
                </div>

                <div>
                  <h3 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-2">
                    Education
                  </h3>
                  {generatedResume?.education?.map((edu: string, idx: number) => (
                    <p key={idx} className="text-sm text-gray-700 mb-1">{edu}</p>
                  )) || <p className="text-sm text-gray-500">Generating education...</p>}
                </div>
              </div>
            )}

            {activeTab === "cover" && (
              <div className="max-w-[210mm] mx-auto my-6 p-12 bg-white min-h-full shadow-2xl rounded-lg font-sans text-slate-800 leading-relaxed whitespace-pre-wrap">
                {generatedCoverLetter?.fullText || "Generating cover letter..."}
              </div>
            )}

            {activeTab === "latex" && (
              <div className="bg-slate-950 text-slate-300 p-6 min-h-full font-mono text-xs overflow-auto">
                <pre>{latexCode}</pre>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
  /* #endregion */
}
