"use client";

import { useState, useEffect } from "react";
import {
  ArrowLeft,
  Cpu,
  Download,
  Edit3,
  ExternalLink,
  FileCode,
  FileText,
  ShieldAlert,
} from "lucide-react";
import { Button } from "@acme/ui/button";
import { Card } from "@acme/ui/card";
import { calculateFit, type Job } from "../_lib/mock-data";

interface GeneratorViewProps {
  job: Job;
  userDump: string;
  onBack: () => void;
}

/**
 * Render a generator UI that simulates content generation then displays generated resume, cover letter, and LaTeX outputs populated from the provided job and user data.
 *
 * The component shows a progressive loading state (with animated progress and step indicators) while generating content, then presents a two-column layout containing job context, AI strategy, and a tabbed output area with "PDF Preview", "Cover Letter", and "LaTeX" views. The active tab can be switched and a provided back callback is invoked when the Back action is triggered.
 *
 * @param job - Job data used to populate the preview, cover letter, and LaTeX templates (title, company, keywords, tags, location, description, risk metadata, and application link)
 * @param userDump - Freeform user data string used to tailor generated content
 * @param onBack - Callback invoked when the Back button is clicked
 * @returns The React element tree for the generator view
 */
export function GeneratorView({ job, userDump, onBack }: GeneratorViewProps) {
  const [activeTab, setActiveTab] = useState<"preview" | "latex" | "cover">(
    "preview",
  );
  const [isGenerating, setIsGenerating] = useState(true);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const intervals = [
      { t: 500, p: 20 },
      { t: 1000, p: 40 },
      { t: 1500, p: 60 },
      { t: 2000, p: 80 },
      { t: 2500, p: 100 },
    ];

    intervals.forEach(({ t, p }) => {
      setTimeout(() => {
        setProgress(p);
        if (p === 100) setIsGenerating(false);
      }, t);
    });
  }, []);

  const latexCode = `
% Auto-generated by KerjaFlow via Claude Sonnet
\\documentclass[a4paper,10pt]{article}
\\usepackage{titlesec}
\\usepackage{geometry}
\\usepackage{enumitem}
\\geometry{left=1in, right=1in, top=1in, bottom=1in}

\\begin{document}

\\section*{Candidate Name}
\\textbf{Role Applied:} ${job.title} at ${job.company}

\\section*{Professional Summary}
Results-oriented professional with ${userDump.includes("4 years") ? "4 years" : "proven"} experience.
Specific expertise in ${job.keywords.slice(0, 2).join(" and ")}, directly matching the requirements for the ${job.title} role.

\\section*{Relevant Experience}
\\textbf{TechMy Sdn Bhd} \\hfill 2020--2022 \\\\
\\textit{Frontend Developer}
\\begin{itemize}[noitemsep]
    \\item Leveraged ${job.tags[0] || "React"} to build scalable systems.
    \\item (AI Tailored): Optimized performance, aligning with ${job.company}'s focus on quality.
\\end{itemize}

\\end{document}
  `;

  const coverLetter = `
Dear Hiring Manager at ${job.company},

I am writing to express my strong interest in the ${job.title} position based in ${job.location}.

I noticed in the job description that ${job.company} values "${job.culture_raw || "innovation"}". This resonates with me because in my previous role, I always prioritized transparent communication and high-quality code delivery.

With my background in ${job.keywords[0]} and ${job.keywords[1]}, I am confident I can hit the ground running.

Thank you for your time and consideration.

Sincerely,
[Candidate Name]
  `;

  // #region LOADING STATE
  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh]">
        <div className="w-64 border-2 border-foreground h-2 mb-8 overflow-hidden">
          <div
            className="bg-accent h-full transition-all duration-300 ease-out"
            style={{ width: `${progress}%` }}
          ></div>
        </div>
        <div className="flex flex-col items-center space-y-6">
          <Cpu size={40} className="text-accent" />
          <h2 className="text-lg font-bold text-foreground">
            Claude is generating...
          </h2>
          <div className="text-sm text-muted-foreground flex flex-col items-start space-y-2">
            <p className={progress > 20 ? "text-accent" : ""}>
              {progress > 20 ? "✓" : "○"} Analyzing Master Dump
            </p>
            <p className={progress > 40 ? "text-accent" : ""}>
              {progress > 40 ? "✓" : "○"} Matching keywords: {job.keywords.slice(0, 3).join(", ")}
            </p>
            <p className={progress > 60 ? "text-accent" : ""}>
              {progress > 60 ? "✓" : "○"} Drafting cover letter
            </p>
            <p className={progress > 80 ? "text-accent" : ""}>
              {progress > 80 ? "✓" : "○"} Compiling LaTeX to PDF
            </p>
          </div>
        </div>
      </div>
    );
  }
  // #endregion

  return (
    <div className="max-w-6xl mx-auto h-[85vh] flex flex-col">
      {/* #region TOP BAR */}
      <div className="flex items-center justify-between mb-4">
        <button
          onClick={onBack}
          className="flex items-center text-muted-foreground hover:text-foreground transition-colors text-sm"
        >
          <ArrowLeft size={14} className="mr-1" /> Back to Results
        </button>
        <Button asChild variant="accent">
          <a
            href={job.link}
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-2"
          >
            Apply on Hiredly <ExternalLink size={14} />
          </a>
        </Button>
      </div>
      {/* #endregion */}

      <div className="grid grid-cols-12 gap-4 h-full pb-8">
        {/* #region LEFT PANEL */}
        <div className="col-span-12 md:col-span-4 flex flex-col gap-4 h-full overflow-hidden">
          <Card className="p-0">
            <div className="p-4 border-b border-muted">
              <h1 className="text-sm font-medium text-foreground leading-tight mb-1">
                {job.title}
              </h1>
              <p className="text-xs text-muted-foreground">{job.company}</p>
            </div>

            <div className="p-4 border-b border-muted flex items-center justify-between">
              <span className="text-xs font-medium text-muted-foreground">
                Fit Score
              </span>
              <span className="text-xl font-bold text-accent tabular-nums">
                {calculateFit(job.keywords, userDump)}%
              </span>
            </div>

            {job.risk_level === "High Risk" && (
              <div className="p-4 border-b border-destructive bg-destructive/5">
                <h4 className="flex items-center text-destructive font-medium text-xs mb-2">
                  <ShieldAlert size={12} className="mr-1" /> Red Flags
                </h4>
                <ul className="space-y-1">
                  {job.red_flags.map((flag, idx) => (
                    <li key={idx} className="text-xs text-destructive">
                      • {flag}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="p-4 text-xs text-muted-foreground leading-relaxed max-h-32 overflow-y-auto">
              {job.description}
            </div>
          </Card>

          <Card className="p-0 flex-1 overflow-auto border-accent">
            <div className="p-4 border-b border-accent flex items-center gap-2">
              <Cpu size={14} className="text-accent" />
              <h3 className="font-medium text-accent text-xs">
                AI Strategy
              </h3>
            </div>
            <div className="p-4 space-y-3 text-xs text-foreground leading-relaxed">
              <p>
                Rephrased experience at <strong>TechMy</strong> to highlight{" "}
                <strong>{job.tags[0]}</strong> (critical requirement).
              </p>
              <p>
                Emphasized &quot;team leadership&quot; over &quot;freelance&quot; work for senior role positioning.
              </p>
            </div>
          </Card>
        </div>
        {/* #endregion */}

        {/* #region RIGHT PANEL */}
        <div className="col-span-12 md:col-span-8 flex flex-col border-2 border-foreground overflow-hidden">
          <div className="bg-foreground text-background p-3 flex justify-between items-center">
            <div className="flex gap-1">
              {[
                { id: "preview", icon: FileText, label: "PDF Preview" },
                { id: "cover", icon: Edit3, label: "Cover Letter" },
                { id: "latex", icon: FileCode, label: "LaTeX" },
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as typeof activeTab)}
                  className={`px-3 py-1.5 text-xs font-medium flex items-center gap-1.5 transition-colors ${
                    activeTab === tab.id
                      ? "bg-background text-foreground"
                      : "text-background/60 hover:text-background"
                  }`}
                >
                  <tab.icon size={12} /> {tab.label}
                </button>
              ))}
            </div>
            <button className="text-accent text-xs font-medium flex items-center gap-1.5 hover:text-background transition-colors">
              <Download size={12} /> Download
            </button>
          </div>

          <div className="flex-1 bg-card overflow-y-auto">
            {activeTab === "preview" && (
              <div className="max-w-[210mm] mx-auto p-12 bg-card min-h-full">
                <div className="text-center border-b-2 border-foreground pb-6 mb-6">
                  <h2 className="text-xl font-bold text-foreground">
                    Demo User
                  </h2>
                  <div className="text-xs text-muted-foreground mt-2 flex justify-center gap-4">
                    <span>Subang Jaya, MY</span>
                    <span>|</span>
                    <span>candidate@email.com</span>
                    <span>|</span>
                    <span>linkedin.com/in/demo</span>
                  </div>
                </div>

                <div className="mb-6">
                  <h3 className="text-xs font-bold text-muted-foreground mb-2 border-b border-muted pb-1">
                    Summary
                  </h3>
                  <p className="text-xs leading-relaxed text-foreground">
                    Results-oriented Software Engineer with proven track record.
                    Expertise in{" "}
                    <strong>{job.keywords.slice(0, 3).join(", ")}</strong>,
                    aligning with <strong>{job.title}</strong> at{" "}
                    <strong>{job.company}</strong>.
                  </p>
                </div>

                <div className="mb-6">
                  <h3 className="text-xs font-bold text-muted-foreground mb-3 border-b border-muted pb-1">
                    Experience
                  </h3>

                  <div className="mb-4">
                    <div className="flex justify-between items-baseline mb-1">
                      <h4 className="font-medium text-foreground text-sm">
                        Frontend Developer
                      </h4>
                      <span className="text-xs text-muted-foreground">
                        2020 - 2022
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mb-2">
                      TechMy Sdn Bhd
                    </p>
                    <ul className="text-xs space-y-1 text-foreground">
                      <li>
                        • Built dashboard using <strong>{job.tags[0] || "React"}</strong>, reducing load times by 40%
                      </li>
                      <li>
                        • Implemented <strong>{job.tags[1] || "RESTful APIs"}</strong> for data integration
                      </li>
                      <li>
                        • Mentored juniors on {job.keywords[1] || "web dev"} best practices
                      </li>
                    </ul>
                  </div>
                </div>

                <div>
                  <h3 className="text-xs font-bold text-muted-foreground mb-2 border-b border-muted pb-1">
                    Skills
                  </h3>
                  <p className="text-xs text-foreground">
                    {job.keywords.join(" | ")} | SQL | Git | Tailwind
                  </p>
                </div>
              </div>
            )}

            {activeTab === "cover" && (
              <div className="max-w-[210mm] mx-auto p-12 bg-card min-h-full text-sm text-foreground leading-relaxed whitespace-pre-wrap">
                {coverLetter}
              </div>
            )}

            {activeTab === "latex" && (
              <div className="bg-foreground text-background p-6 min-h-full text-xs overflow-auto">
                <pre>{latexCode}</pre>
              </div>
            )}
          </div>
        </div>
        {/* #endregion */}
      </div>
    </div>
  );
}